{
 "title": "Dashbord FNAC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "product to be published", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "product to be published",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT name, sold_by\nFROM electronics\nWHERE published_at IS NULL OR published_at = ''\nUNION\nSELECT name, sold_by\nFROM books\nWHERE published_at IS NULL OR published_at = ''\nUNION\nSELECT name, sold_by\nFROM cds\nWHERE published_at IS NULL OR published_at = '';\n",
     "rawQueryText": "SELECT name, sold_by\nFROM electronics\nWHERE published_at IS NULL OR published_at = ''\nUNION\nSELECT name, sold_by\nFROM books\nWHERE published_at IS NULL OR published_at = ''\nUNION\nSELECT name, sold_by\nFROM cds\nWHERE published_at IS NULL OR published_at = '';\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "graph of quantities for each catégories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "quantity cds",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT quantity,name FROM cds",
     "rawQueryText": "SELECT quantity,name FROM cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "quantity electronics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT quantity,name FROM electronics",
     "rawQueryText": "SELECT quantity,name FROM electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "quantity books",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT quantity,name FROM books",
     "rawQueryText": "SELECT quantity,name FROM books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "graph of quantities for each supplier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "PC.CLINIC product",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'PC.CLINIC'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'PC.CLINIC'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'PC.CLINIC';",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'PC.CLINIC'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'PC.CLINIC'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'PC.CLINIC';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "samsung product",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'samsung'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'samsung'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'samsung';\n",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'samsung'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'samsung'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'samsung';\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "BilletReduc product",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'BilletReduc'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'BilletReduc'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'BilletReduc';",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'BilletReduc'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'BilletReduc'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'BilletReduc';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "dreamwork product",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'dreamwork'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'dreamwork'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'dreamwork';",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'dreamwork'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'dreamwork'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'dreamwork';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Nature & Découvertes product",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'Nature & Découvertes'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'Nature & Découvertes'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'Nature & Découvertes';",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'Nature & Découvertes'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'Nature & Découvertes'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'Nature & Découvertes';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "france billet product",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "queryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'francebillet'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'francebillet'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'francebillet';",
     "rawQueryText": "SELECT e.name AS electronics_name, e.quantity AS electronics_quantity\nFROM electronics e\nWHERE e.sold_by = 'francebillet'\nUNION\nSELECT b.name AS books_name, b.quantity AS books_quantity\nFROM books b\nWHERE b.sold_by = 'francebillet'\nUNION\nSELECT c.name AS cds_name, c.quantity AS cds_quantity\nFROM cds c\nWHERE c.sold_by = 'francebillet';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}